### ISSUE TITLE
Cannot load such file -- escape_utils/escape_utils (LoadError)

### ISSUE THREAD

**Issue by hoenth** [brianmario/escape_utils#86]
On a Mac Intel Core I9 machine, I can install the gem without issue using bundler or `gem install escape_utils`

However, when I attempt to boot the application, I get the following error during bootsnap loading of dependencies:
```
05:43 $ bundle exec rails c
Traceback (most recent call last):
	28: from bin/rails:4:in `<main>'
	27: from /Users/darwin/.rbenv/versions/2.7.5/gemsets/evo/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	26: from /Users/darwin/.rbenv/versions/2.7.5/gemsets/evo/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	25: from /Users/darwin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-6.0.6/lib/rails/commands.rb:18:in `<main>'
	24: from /Users/darwin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-6.0.6/lib/rails/command.rb:46:in `invoke'
	23: from /Users/darwin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-6.0.6/lib/rails/command/base.rb:69:in `perform'
	22: from /Users/darwin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	21: from /Users/darwin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	20: from /Users/darwin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	19: from /Users/darwin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-6.0.6/lib/rails/commands/console/console_command.rb:101:in `perform'
	18: from /Users/darwin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-6.0.6/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
	17: from /Users/darwin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-6.0.6/lib/rails/command/actions.rb:22:in `require_application!'
	16: from /Users/darwin/.rbenv/versions/2.7.5/gemsets/evo/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	15: from /Users/darwin/.rbenv/versions/2.7.5/gemsets/evo/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	14: from /Users/nfg-projects/Givecorps-site/config/application.rb:7:in `<main>'
	13: from /Users/darwin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.26/lib/bundler.rb:186:in `require'
	12: from /Users/darwin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/runtime.rb:44:in `require'
	11: from /Users/darwin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/runtime.rb:44:in `each'
	10: from /Users/darwin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/runtime.rb:55:in `block in require'
	 9: from /Users/darwin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/runtime.rb:55:in `each'
	 8: from /Users/darwin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	 7: from /Users/darwin/.rbenv/versions/2.7.5/gemsets/evo/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	 6: from /Users/darwin/.rbenv/versions/2.7.5/gemsets/evo/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	 5: from /Users/darwin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/escape_utils-0.2.4/lib/escape_utils.rb:1:in `<main>'
	 4: from /Users/darwin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-6.0.6/lib/active_support/dependencies.rb:324:in `require'
	 3: from /Users/darwin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-6.0.6/lib/active_support/dependencies.rb:291:in `load_dependency'
	 2: from /Users/darwin/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-6.0.6/lib/active_support/dependencies.rb:324:in `block in require'
	 1: from /Users/darwin/.rbenv/versions/2.7.5/gemsets/evo/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/Users/darwin/.rbenv/versions/2.7.5/gemsets/evo/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require': cannot load such file -- escape_utils/escape_utils (LoadError)
```

On my M1 machine, I have never encountered this issue. 

I've installing the gem with the verbose setting, but I am not seeing anything there either. I see that there is no escape_utils/escape_utils.rb file in the gem, though there is an escape_utils.bundle file. 

Any advice, or suggestions would be greatly appreciated.

**Comment by byroot** [comment]
From an Intel mac, works fine:

```ruby
>> require 'escape_utils'
=> true
>> $LOADED_FEATURES.grep(/escape_utils/)
=> 
["/Users/byroot/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/escape_utils-1.3.0/lib/escape_utils/escape_utils.bundle",
 "/Users/byroot/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/escape_utils-1.3.0/lib/escape_utils/version.rb",
 "/Users/byroot/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/escape_utils-1.3.0/lib/escape_utils.rb"]
```

I suspect your bootsnap cache is corrupted somehow, not sure how you got there, perhaps by using docker with another arch in the same directory or something like that. Try with `DISABLE_BOOTSNAP=1` to confirm whether that's the problem.

Either way, I'm quite certain it's not an issue with the gem, but with your setup.

**Comment by hoenth** [comment]
Thank you @byroot for quickly confirming that it is not machine specific. Going through clearing caches, uninstalling and reinstalling ruby, etc. Will also try with DISABLE_BOOTSNAP=1 if the above provides no love.
